# Generated by Django 2.0.3 on 2019-09-04 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('read_statistics', '0002_readdetaill'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReadDetaill',
            new_name='ReadDetail',
        ),
    ]
