# Generated by Django 2.0.3 on 2019-08-23 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='bolg_type',
            new_name='blog_type',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='last_uodated_time',
            new_name='last_updated_time',
        ),
    ]
